### PR TITLE
Gomspacelogger

### PR DESCRIPTION
**Pull request by knk38**
# Adding Gomspace Logging Test Case

### Summary of changes
- New test case that reads important gomspace fields for the gomspace charging capability test
- Add test case to init

### CODE REVIEW

**Comment by kylekrol** [comment]
Is there a chance that we would want to create more of these cases in the future? If so, we could make a base case like `LoggerCase` that you can inherit from and then just pass a list of state fields to the parent class - not a request just a thought.

**Review by shihaocao — APPROVED** [review]
Looks good to me

**Comment by shihaocao** [comment]
> Is there a chance that we would want to create more of these cases in the future? If so, we could make a base case like `LoggerCase` that you can inherit from and then just pass a list of state fields to the parent class - not a request just a thought.

We could totally do that on a next PR, getting this in to prep for spotlight testing today

**Comment by knk38** [comment]
> > Is there a chance that we would want to create more of these cases in the future? If so, we could make a base case like `LoggerCase` that you can inherit from and then just pass a list of state fields to the parent class - not a request just a thought.
> 
> We could totally do that on a next PR, getting this in to prep for spotlight testing today

Agreed, I'll merge this in for now.

**Pull request merged**
