### PR TITLE
Quakefault

### PR DESCRIPTION
**Pull request by 18kudlugim**
# Quake Fault Handler Changes
Fixes #. (Optional; sometimes PRs don't have an associated ticket)

### Summary of changes
- Sets quake to disabled before powercycling, then to config once powercycling is over.
- No longer requires quake to be in wait for quake fault handler to powercycle device.

### Testing
Have to change unit testing to represent new changes bc we are not requiring quake to be in wait in order for power cycling to occur. The quake can be in any state before power cycling.

### CODE REVIEW

**Review by kylekrol — APPROVED** [review]
Looks good to me!

**Review by shihaocao — APPROVED** [review]
Everything in here looks good to me. Can we move this to a full PR and get it merged?

To clarify, it passes on HITL, but not on HOOTL?

**Comment by 18kudlugim** [comment]
Expected behavior for power cycling with these changes do not work in HOOTL but should work in HITL due to power cycle flags being extraneously reset in HOOTL.

**Comment by shihaocao** [comment]
> Expected behavior for power cycling with these changes do not work in HOOTL but should work in HITL due to power cycle flags being extraneously reset in HOOTL.

Gotcha. When do we plan on HITLing?

**Pull request merged**
